spring:
  application:
    name: jpaorder
  datasource:
    url: jdbc:postgresql://localhost:5432/jpaorders
    username: postgres
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      properties.hibernate.format_sql: true